Import('env')

# scons -Q release=0 (default)
# scons -Q release=1

filesStr = """
main.cpp
context.cpp
core.cpp
entities.cpp
game.cpp
renderqueue.cpp
screen.cpp
shaders.cpp

../third/imgui/imgui.cpp
../third/imgui/imgui_impl_glfw.cpp
"""

env.Program('daisy', Split(filesStr))
